# typos config
# https://github.com/crate-ci/typos/blob/master/docs/reference.md

[files]
ignore-dot = false
extend-exclude = ["migration/**"]

[default.extend-words]
# North Dakota
nd = "nd"
# santa claus
claus = "claus"
