use sea_orm_migration::prelude::*;
use sea_query::{OnConflict, Query};
use uuid::Uuid;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let rows = vec![
            // New cities
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "Illinois".into(),
                "Brookfield".into(),
                "IL".into(),
                "1708576".into(),
                25.into(),
                41.824867.into(),
                (-87.853447).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Briarcliff-Manor".into(),
                "NY".into(),
                "3608103".into(),
                25.into(),
                41.140232.into(),
                (-73.840231).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Brighton".into(),
                "NY".into(),
                "3608257".into(),
                25.into(),
                43.147560.into(),
                (-77.550550).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Bronxville".into(),
                "NY".into(),
                "3608532".into(),
                25.into(),
                40.938150.into(),
                (-73.832080).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Cohoes".into(),
                "NY".into(),
                "3616749".into(),
                25.into(),
                42.774240.into(),
                (-73.700120).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Croton-On-Hudson".into(),
                "NY".into(),
                "3619213".into(),
                25.into(),
                41.208430.into(),
                (-73.891250).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "East-Greenbush".into(),
                "NY".into(),
                "3622106".into(),
                25.into(),
                42.590910.into(),
                (-73.701230).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Greenport".into(),
                "NY".into(),
                "3630576".into(),
                25.into(),
                41.103990.into(),
                (-72.361640).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Lewiston".into(),
                "NY".into(),
                "3642147".into(),
                25.into(),
                43.172000.into(),
                (-79.036710).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Mamaroneck".into(),
                "NY".into(),
                "3644831".into(),
                25.into(),
                40.948710.into(),
                (-73.732630).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Millbrook".into(),
                "NY".into(),
                "3647273".into(),
                25.into(),
                41.785650.into(),
                (-73.694570).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Northville".into(),
                "NY".into(),
                "3653770".into(),
                25.into(),
                43.225350.into(),
                (-74.172640).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Schenectady".into(),
                "NY".into(),
                "3665508".into(),
                25.into(),
                42.814240.into(),
                (-73.939570).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Tarrytown".into(),
                "NY".into(),
                "3673176".into(),
                25.into(),
                41.076210.into(),
                (-73.858750).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Tivoli".into(),
                "NY".into(),
                "3674023".into(),
                25.into(),
                42.059810.into(),
                (-73.909580).into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "White-Plains".into(),
                "NY".into(),
                "3681677".into(),
                25.into(),
                41.033990.into(),
                (-73.762910).into(),
            ],
            // Existing cities
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "Arkansas".into(),
                "Rogers".into(),
                "AR".into(),
                "560410".into(),
                20.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "Massachusetts".into(),
                "Amesbury-Town".into(),
                "MA".into(),
                "2501185".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New Jersey".into(),
                "Hoboken".into(),
                "NJ".into(),
                "3432250".into(),
                20.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Albany".into(),
                "NY".into(),
                "3601000".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Hudson".into(),
                "NY".into(),
                "3635969".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Ithaca".into(),
                "NY".into(),
                "3638077".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Kingston".into(),
                "NY".into(),
                "3639727".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "New-Paltz".into(),
                "NY".into(),
                "3650551".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Scarsdale".into(),
                "NY".into(),
                "3665431".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "New York".into(),
                "Scotia".into(),
                "NY".into(),
                "3665893".into(),
                25.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
            vec![
                Uuid::new_v4().into(),
                "United States".into(),
                "Oregon".into(),
                "Lake-Oswego".into(),
                "OR".into(),
                "4140550".into(),
                20.into(),
                None::<f64>.into(),
                None::<f64>.into(),
            ],
        ];

        let mut stmt = Query::insert();

        stmt.into_table(City::Table)
            .columns([
                City::Id,
                City::Country,
                City::State,
                City::Name,
                City::StateAbbrev,
                City::FipsCode,
                City::ResidentialSpeedLimit,
                City::Latitude,
                City::Longitude,
            ])
            .values_from_panic(rows)
            .on_conflict(
                OnConflict::columns([City::Country, City::State, City::Name])
                    .update_columns([
                        City::Name,
                        City::State,
                        City::StateAbbrev,
                        City::ResidentialSpeedLimit,
                        City::Latitude,
                        City::Longitude,
                    ])
                    .to_owned(),
            );

        manager.exec_stmt(stmt).await?;

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // This is a data migration only, there is nothing to revert.
        Ok(())
    }
}

#[derive(Iden)]
enum City {
    Table,
    Id,
    Country,
    State,
    Name,
    StateAbbrev,
    FipsCode,
    ResidentialSpeedLimit,
    Latitude,
    Longitude,
}
