@host=https://api.peopleforbikes.xyz
# Walla Walla, WA.
@city_id=1c8f4f93-3537-4f31-ba0c-e165ebf67b74
@bna_id=5864c9b6-ccb7-473f-a4fb-fec0345fc786

###
# Query the first page of the bnas.
GET {{host}}/bnas

###
# Query a specific bna run.
GET {{host}}/bnas/{{bna_id}}

###
# Query a specific bna run and its associated city.
GET {{host}}/bnas/{{bna_id}}/city

###
# Query the first page of the cities.
GET {{host}}/cities

###
# Query a specific city.
GET {{host}}/cities/{{city_id}}

###
# Query all the BNAs of a specific city.
GET {{host}}/cities/{{city_id}}/bnas

###
# Query all the submissions.
GET {{host}}/cities/submissions
content-type: application/json

###
# Query all the pending submissions.
GET {{host}}/cities/submissions?status=Pending
content-type: application/json

###
# Query a specific submission.
GET {{host}}/cities/submissions/1
content-type: application/json

###
# Create a new submission.
POST {{host}}/cities/submissions
content-type: application/json

{
  "city": "santa rosa",
  "country": "usa",
  "email": "jane.dpe@orgllc.com",
  "fips_code": "3570670",
  "first_name": "Jane",
  "last_name": "Doe",
  "organization": "Organization LLC",
  "region": "new mexico",
  "title": "CTO",
  "consent": true
}

###
# https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_ResponseSyntax
# @name cognito_auth
POST https://cognito-idp.us-west-2.amazonaws.com/
content-type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

{
  "AuthParameters" : {
      "USERNAME" : "{{$dotenv USERNAME}}",
      "PASSWORD" : "{{$dotenv PASSWORD}}"
  },
  "AuthFlow" : "USER_PASSWORD_AUTH",
  "ClientId" : "{{$dotenv CLIENT_ID}}"
}

###
# https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#CognitoUserPools-RespondToAuthChallenge-request-ChallengeResponses
# @name cognito_mfa
# @prompt mfa_code software MFA code
POST https://cognito-idp.us-west-2.amazonaws.com/
content-type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.RespondToAuthChallenge

{
  "ChallengeName": "SOFTWARE_TOKEN_MFA",
  "ChallengeResponses": {
    "USERNAME": "{{$dotenv USERNAME}}",
    "SOFTWARE_TOKEN_MFA_CODE": "{{mfa_code}}"
  },
  "ClientId": "{{$dotenv CLIENT_ID}}",
  "Session": "{{cognito_auth.response.body.Session}}"
}

###
@cognito_access = {{cognito_mfa.response.body.AuthenticationResult.AccessToken}}
@cognito_id = {{cognito_mfa.response.body.AuthenticationResult.IdToken}}
@cognito_refresh = {{cognito_mfa.response.body.AuthenticationResult.RefreshToken}}

###
# Enqueue a new city to be analyzed.
POST {{host}}/cities/enqueue
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "city": "santa rosa",
  "country": "usa",
  "fips_code": "3570670",
  "region": "new mexico"
}

###
# Collect the list of analysis that completed.
GET {{host}}/bnas/results
content-type: application/json
Authorization: Bearer {{cognito_access}}

###
# Update a specific submission.
PATCH  {{host}}/cities/submissions/1
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "city": "santa rosa",
  "country": "usa",
  "email": "jane.dpe@orgllc.com",
  "fips_code": "3570670",
  "first_name": "Jane",
  "last_name": "Doe",
  "organization": "Organization LLC",
  "region": "new mexico",
  "title": "CTO",
  "consent": true,
  "status": "Accepted"
}


################################################################################
# Bellow this point are the tests from schemathesis.
################################################################################

GET {{host}}/bnas/1
X-Schemathesis-TestCaseId: 3bf4a72a4cc04ed589c5eedaf57b3ca2

###
GET {{host}}/bnas/0/city
X-Schemathesis-TestCaseId: 9fa24d92de444fd28180df72fa1fabd6

###
GET {{host}}/cities
X-Schemathesis-TestCaseId: 6c4cbf8880594f3d921ed1c3fe474a7f

###
GET {{host}}/cities/0
X-Schemathesis-TestCaseId: 6c4cbf8880594f3d921ed1c3fe474a7f

###
GET {{host}}/cities/0/bnas
X-Schemathesis-TestCaseId: 1f951094a7f14597bb50cafc52b812e0
