# @host=https://api.peopleforbikes.xyz
@host=http://localhost:3000
# Austin, TX, USA.
@city_id=ef8384d5-b96f-439d-a83b-bc801735ddc6
@rating_id=1a759b85-cd87-4bb1-9efa-5789e38e9982
@country=United States
@region=Texas
@name=Austin

###
# Query the first page of the bnas.
GET {{host}}/ratings


###
# Query the first page of the bnas.
GET {{host}}/ratings?page_size=1257596201

###
# Query a specific bna run.
GET {{host}}/ratings/{{rating_id}}

###
# Query a specific bna run and its associated city.
GET {{host}}/ratings/{{rating_id}}/city

###
# Query the first page of the cities.
GET {{host}}/cities

###
# Query a specific city.
GET {{host}}/cities/{{country}}/{{region}}/{{name}}

###
# Query all the BNAs of a specific city.
GET {{host}}/cities/{{country}}/{{region}}/{{name}}/ratings

###
# Query all the Census of a specific city.
GET {{host}}/cities/{{country}}/{{region}}/{{name}}/census

###
# Query all the submissions.
GET {{host}}/cities/submissions

###
# Query all the pending submissions.
GET {{host}}/cities/submissions?status=Pending

###
# Query a specific submission.
GET {{host}}/cities/submissions/1

###
# Query Fargate prices.
GET {{host}}/prices/fargate

###
# Create a new submission.
POST {{host}}/cities/submissions
content-type: application/json

{
  "city": "santa rosa",
  "country": "usa",
  "email": "jane.dpe@orgllc.com",
  "fips_code": "3570670",
  "first_name": "Jane",
  "last_name": "Doe",
  "organization": "Organization LLC",
  "region": "new mexico",
  "title": "CTO",
  "consent": true
}

###
# https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_ResponseSyntax
# @name cognito_auth
POST https://cognito-idp.us-west-2.amazonaws.com/
content-type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

{
  "AuthParameters" : {
      "USERNAME" : "{{$dotenv USERNAME}}",
      "PASSWORD" : "{{$dotenv PASSWORD}}"
  },
  "AuthFlow" : "USER_PASSWORD_AUTH",
  "ClientId" : "{{$dotenv CLIENT_ID}}"
}

###
# https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#CognitoUserPools-RespondToAuthChallenge-request-ChallengeResponses
# @name cognito_mfa
# @prompt mfa_code software MFA code
POST https://cognito-idp.us-west-2.amazonaws.com/
content-type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.RespondToAuthChallenge

{
  "ChallengeName": "SOFTWARE_TOKEN_MFA",
  "ChallengeResponses": {
    "USERNAME": "{{$dotenv USERNAME}}",
    "SOFTWARE_TOKEN_MFA_CODE": "{{mfa_code}}"
  },
  "ClientId": "{{$dotenv CLIENT_ID}}",
  "Session": "{{cognito_auth.response.body.Session}}"
}

###
@cognito_access = {{cognito_mfa.response.body.AuthenticationResult.AccessToken}}
@cognito_id = {{cognito_mfa.response.body.AuthenticationResult.IdToken}}
@cognito_refresh = {{cognito_mfa.response.body.AuthenticationResult.RefreshToken}}

###
# Enqueue a new city to be analyzed.
POST {{host}}/cities/enqueue
content-type: application/json
Authorization: Bearer {{cognito_access}}

[
  {
  "city": "santa rosa",
  "country": "United States",
  "fips_code": "3570670",
  "region": "new mexico"
  }
]

###
# Collect the list of analysis that completed.
GET {{host}}/ratings/results
Authorization: Bearer {{cognito_access}}

###
# Update a specific submission.
PATCH  {{host}}/cities/submissions/1
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "city": "santa rosa",
  "country": "United States",
  "email": "jane.dpe@orgllc.com",
  "fips_code": "3570670",
  "first_name": "Jane",
  "last_name": "Doe",
  "organization": "Organization LLC",
  "region": "new mexico",
  "title": "CTO",
  "consent": true,
  "status": "Accepted"
}

@state_machine_id=e6aade5a-b343-120b-dbaa-bd916cd99221

### Create a new BNA analysis performed by the Brokenspoke-analyzer pipeline.
POST {{host}}/pipelines/bna
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "cost": 10.345,
  "start_time": "2024-12-09T14:16:11.133641Z",
  "state_machine_id": "804594ed-b3a6-4138-a9d3-454a0578e5f7",
  "step": "Setup"
}

### Query the BNA analysis performed by the Brokenspoke-analyzer pipeline.
GET {{host}}/ratings/analyses
Authorization: Bearer {{cognito_access}}

### Query a specific BNA analysis performed by the Brokenspoke-analyzer pipeline.
GET {{host}}/ratings/analyses/{{state_machine_id}}
Authorization: Bearer {{cognito_access}}

### Update an existing BNA analysis performed by the Brokenspoke-analyzer pipeline.
PATCH {{host}}/ratings/analysis/{{state_machine_id}}
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "neon_branch_id": "br-aged-salad-637688"
}



###
#
PATCH {{host}}/ratings/analyses/c86473dd-53b5-4abd-be0d-c25ed6b5f029
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "cost": 10.345,
  "results_posted": true,
  "start_time": "2024-12-09T18:02:22.607245Z",
  "status": "Completed",
  "step": "Setup"
}

### Create a new BNA .
POST {{host}}/ratings
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
  "city_id": "09c049b6-213b-405c-bc4e-178346ff814d",
  "core_services": {
    "dentists": 0,
    "doctors": 0,
    "grocery": 1.69,
    "hospitals": 5.18,
    "pharmacies": 0,
    "score": 3.24
  },
  "infrastructure": {
    "high_stress_miles": 64.5,
    "low_stress_miles": 9.3
  },
  "opportunity": {
    "employment": 8.26,
    "higher_education": 0,
    "k12_education": 8.31,
    "score": 8.29,
    "technical_vocational_college": 0
  },
  "people": {
    "people": 19.17
  },
  "recreation": {
    "community_centers": 0,
    "parks": 7.13,
    "score": 7.13,
    "trails": 0
  },
  "retail": {
    "retail": 0
  },
  "transit": {
    "transit": 0
  },
  "measure": {},
  "pop_size": 2,
  "population": 123456,
  "version": "24.12",
  "score": 8.93
}

### Create a new city.
POST {{host}}/cities/
content-type: application/json
Authorization: Bearer {{cognito_access}}

{
    "country": "Spain",
    "latitude": 39.46975 9,
    "longitude": -0.3773,
    "name": "Valencia",
    "region": "Europe",
    "state": "Valencia",
    "state_abbrev": "VC",
    "speed_limit": null,
}

################################################################################
# Bellow this point are the tests from schemathesis.
################################################################################

GET {{host}}/ratings/1
X-Schemathesis-TestCaseId: 3bf4a72a4cc04ed589c5eedaf57b3ca2

###
GET {{host}}/ratings/0/city
X-Schemathesis-TestCaseId: 9fa24d92de444fd28180df72fa1fabd6

###
GET {{host}}/cities
X-Schemathesis-TestCaseId: 6c4cbf8880594f3d921ed1c3fe474a7f

###
GET {{host}}/cities/0
X-Schemathesis-TestCaseId: 6c4cbf8880594f3d921ed1c3fe474a7f

###
GET {{host}}/cities/0/ratings
X-Schemathesis-TestCaseId: 1f951094a7f14597bb50cafc52b812e0
