//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod census;
pub mod city;
pub mod core_services;
pub mod features;
pub mod infrastructure;
pub mod opportunity;
pub mod ranking;
pub mod recreation;
pub mod speed_limit;
pub mod submission;
pub mod summary;
