//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "opportunity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub bna_uuid: Uuid,
    #[sea_orm(column_type = "Double", nullable)]
    pub employment: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub higher_education: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub k12_education: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub score: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub technical_vocational_college: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::summary::Entity",
        from = "Column::BnaUuid",
        to = "super::summary::Column::BnaUuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Summary,
}

impl Related<super::summary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Summary.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
