//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::census::Entity as Census;
pub use super::city::Entity as City;
pub use super::core_services::Entity as CoreServices;
pub use super::features::Entity as Features;
pub use super::infrastructure::Entity as Infrastructure;
pub use super::opportunity::Entity as Opportunity;
pub use super::ranking::Entity as Ranking;
pub use super::recreation::Entity as Recreation;
pub use super::speed_limit::Entity as SpeedLimit;
pub use super::summary::Entity as Summary;
