Table "approval_status" {
  "status" "character varying" [pk, not null]
}

Table "bna_region" {
  "name" "character varying" [pk, not null]
}

Table "brokenspoke_pipeline" {
  "state_machine_id" uuid [pk, not null]
  "step" "character varying"
  "sqs_message" json
  "fargate_task_arn" "character varying"
  "s3_bucket" "character varying"
  "start_time" timestamp [not null]
  "end_time" timestamp
  "torn_down" boolean
  "results_posted" boolean
  "cost" numeric
}

Table "brokenspoke_status" {
  "status" "character varying" [pk, not null]
}

Table "brokenspoke_step" {
  "step" "character varying" [pk, not null]
}

Table "census" {
  "id" integer [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "fips_code" "character varying" [not null]
  "pop_size" integer [not null]
  "population" integer [not null]

  Indexes {
    city_id [type: btree, name: "census_city_id_idx"]
    id [type: btree, name: "census_id_idx"]
  }
}

Table "city" {
  "id" uuid [unique, not null]
  "country" "character varying" [not null]
  "state" "character varying" [not null]
  "name" "character varying" [not null]
  "latitude" doubleprecision
  "longitude" doubleprecision
  "region" "character varying"
  "state_abbrev" "character varying"
  "speed_limit" integer
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp

  Indexes {
    (country, state, name) [pk, name: "city_pkey"]
    id [type: btree, name: "city_id_idx"]
  }
}

Table "core_services" {
  "bna_id" uuid [pk, not null]
  "dentists" doubleprecision
  "doctors" doubleprecision
  "grocery" doubleprecision
  "hospitals" doubleprecision
  "pharmacies" doubleprecision
  "score" doubleprecision
  "social_services" doubleprecision
}

Table "country" {
  "name" "character varying" [pk, not null]
}

Table "fargate_price" {
  "id" integer [pk, not null]
  "per_second" numeric [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "infrastructure" {
  "bna_id" uuid [pk, not null]
  "low_stress_miles" doubleprecision
  "high_stress_miles" doubleprecision
}

Table "opportunity" {
  "bna_id" uuid [pk, not null]
  "employment" doubleprecision
  "higher_education" doubleprecision
  "k12_education" doubleprecision
  "score" doubleprecision
  "technical_vocational_college" doubleprecision
}

Table "people" {
  "bna_id" uuid [pk, not null]
  "people" doubleprecision
}

Table "recreation" {
  "bna_id" uuid [pk, not null]
  "community_centers" doubleprecision
  "parks" doubleprecision
  "recreation_trails" doubleprecision
  "score" doubleprecision
}

Table "retail" {
  "bna_id" uuid [pk, not null]
  "retail" doubleprecision
}

Table "seaql_migrations" {
  "version" "character varying" [pk, not null]
  "applied_at" bigint [not null]
}

Table "speed_limit" {
  "id" integer [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "residential" integer [not null]

  Indexes {
    city_id [type: btree, name: "speed_limit_city_id_idx"]
    id [type: btree, name: "speed_limit_id_idx"]
  }
}

Table "state_region_crosswalk" {
  "state" "character varying" [not null]
  "region" "character varying" [not null]

  Indexes {
    (state, region) [pk, name: "state_region_crosswalk_pkey"]
    region [type: btree, name: "state_region_crosswalk_region_idx"]
    state [type: btree, name: "state_region_crosswalk_state_idx"]
  }
}

Table "submission" {
  "id" integer [pk, not null]
  "first_name" "character varying" [not null]
  "last_name" "character varying" [not null]
  "occupation" "character varying"
  "organization" "character varying"
  "email" "character varying" [not null]
  "country" "character varying" [not null]
  "city" "character varying" [not null]
  "region" "character varying"
  "fips_code" "character varying" [not null, default: `'0'::charactervarying`]
  "consent" boolean [not null]
  "status" "character varying" [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "summary" {
  "bna_id" uuid [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "score" doubleprecision [not null]
  "version" "character varying" [not null]
}

Table "transit" {
  "bna_id" uuid [pk, not null]
  "transit" doubleprecision
}

Table "us_state" {
  "name" "character varying" [pk, not null]
  "abbrev" "character varying" [unique, not null]
  "fips_code" "character varying" [unique, not null]
  "speed_limit" integer [not null]

  Indexes {
    abbrev [type: btree, name: "us_state_abbrev_idx"]
    fips_code [type: btree, name: "us_state_fips_code_idx"]
  }
}

Ref "census_city_id_fkey":"city"."id" < "census"."city_id" [delete: cascade]

Ref "city_country_fkey":"country"."name" < "city"."country"

Ref "core_services_bna_id_fkey":"summary"."bna_id" < "core_services"."bna_id" [delete: cascade]

Ref "infrastructure_bna_id_fkey":"summary"."bna_id" < "infrastructure"."bna_id" [delete: cascade]

Ref "opportunity_bna_id_fkey":"summary"."bna_id" < "opportunity"."bna_id" [delete: cascade]

Ref "people_bna_id_fkey":"summary"."bna_id" < "people"."bna_id" [delete: cascade]

Ref "recreation_bna_id_fkey":"summary"."bna_id" < "recreation"."bna_id" [delete: cascade]

Ref "retail_bna_id_fkey":"summary"."bna_id" < "retail"."bna_id" [delete: cascade]

Ref "speed_limit_city_id_fkey":"city"."id" < "speed_limit"."city_id" [delete: cascade]

Ref "state_region_crosswalk_region_fkey":"bna_region"."name" < "state_region_crosswalk"."region"

Ref "state_region_crosswalk_state_fkey":"us_state"."name" < "state_region_crosswalk"."state"

Ref "submission_country_fkey":"country"."name" < "submission"."country"

Ref "submission_status_fkey":"approval_status"."status" < "submission"."status"

Ref "summary_city_id_fkey":"city"."id" < "summary"."city_id" [delete: cascade]

Ref "transit_bna_id_fkey":"summary"."bna_id" < "transit"."bna_id" [delete: cascade]
