-- SQL dump generated using DBML (dbml-lang.org)
-- Database: PostgreSQL
-- Generated at: 2023-09-02T15:01:52.942Z

CREATE SCHEMA "bna";

CREATE TYPE "size" AS ENUM (
  'small',
  'medium',
  'large'
);

CREATE TABLE "bna"."summary" (
  "bna_uuid" uuid PRIMARY KEY,
  "city_id" uuid,
  "created_at" date,
  "score" float
);

CREATE TABLE "bna"."features" (
  "bna_uuid" uuid PRIMARY KEY,
  "people" float,
  "retail" float,
  "transit" float
);

CREATE TABLE "bna"."core_services" (
  "bna_uuid" uuid PRIMARY KEY,
  "dentists" float,
  "doctors" float,
  "grocery" float,
  "hospitals" float,
  "pharmacies" float,
  "score" float,
  "social_services" float
);

CREATE TABLE "bna"."opportunity" (
  "bna_uuid" uuid PRIMARY KEY,
  "employment" float,
  "higher_education" float,
  "k12_education" float,
  "score" float,
  "technical_vocational_college" float
);

CREATE TABLE "bna"."recreation" (
  "bna_uuid" uuid PRIMARY KEY,
  "community_centers" float,
  "parks" float,
  "recreation_trails" float,
  "score" float
);

CREATE TABLE "bna"."infrastructure" (
  "bna_uuid" uuid PRIMARY KEY,
  "low_stress_miles" float,
  "high_stress_miles" float
);

CREATE TABLE "bna"."city" (
  "city_id" uuid PRIMARY KEY,
  "country" varchar(50),
  "latitude" float,
  "longitude" float,
  "name" varchar(50),
  "region" varchar(50),
  "state" varchar(50),
  "state_abbrev" char(2)
);

CREATE TABLE "bna"."census" (
  "census_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" uuid,
  "created_at" date,
  "fips_code" char(7),
  "pop_size" size,
  "population" int
);

CREATE TABLE "bna"."ranking" (
  "ranking_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" uuid,
  "country" int,
  "country_size" int,
  "created_at" date,
  "global" int,
  "size" int,
  "state" int
);

CREATE TABLE "bna"."speed_limit" (
  "speed_limit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" uuid,
  "created_at" date,
  "residential" int
);

CREATE INDEX ON "bna"."summary" ("bna_uuid");

CREATE INDEX ON "bna"."summary" ("city_id");

CREATE INDEX ON "bna"."features" ("bna_uuid");

CREATE INDEX ON "bna"."core_services" ("bna_uuid");

CREATE INDEX ON "bna"."opportunity" ("bna_uuid");

CREATE INDEX ON "bna"."recreation" ("bna_uuid");

CREATE INDEX ON "bna"."infrastructure" ("bna_uuid");

CREATE INDEX ON "bna"."city" ("city_id");

CREATE INDEX ON "bna"."city" ("name");

CREATE INDEX ON "bna"."census" ("census_id");

CREATE INDEX ON "bna"."census" ("city_id");

CREATE INDEX ON "bna"."census" ("fips_code");

CREATE INDEX ON "bna"."ranking" ("city_id");

CREATE INDEX ON "bna"."ranking" ("ranking_id");

CREATE INDEX ON "bna"."speed_limit" ("city_id");

CREATE INDEX ON "bna"."speed_limit" ("speed_limit_id");

ALTER TABLE "bna"."summary" ADD FOREIGN KEY ("city_id") REFERENCES "bna"."city" ("city_id");

ALTER TABLE "bna"."census" ADD FOREIGN KEY ("city_id") REFERENCES "bna"."city" ("city_id");

ALTER TABLE "bna"."ranking" ADD FOREIGN KEY ("city_id") REFERENCES "bna"."city" ("city_id");

ALTER TABLE "bna"."speed_limit" ADD FOREIGN KEY ("city_id") REFERENCES "bna"."city" ("city_id");

ALTER TABLE "bna"."core_services" ADD FOREIGN KEY ("bna_uuid") REFERENCES "bna"."summary" ("bna_uuid");

ALTER TABLE "bna"."opportunity" ADD FOREIGN KEY ("bna_uuid") REFERENCES "bna"."summary" ("bna_uuid");

ALTER TABLE "bna"."recreation" ADD FOREIGN KEY ("bna_uuid") REFERENCES "bna"."summary" ("bna_uuid");

ALTER TABLE "bna"."infrastructure" ADD FOREIGN KEY ("bna_uuid") REFERENCES "bna"."summary" ("bna_uuid");

ALTER TABLE "bna"."features" ADD FOREIGN KEY ("bna_uuid") REFERENCES "bna"."summary" ("bna_uuid");
