Enum "approval_status" {
  "Pending"
  "Approved"
  "Rejected"
}

Enum "bna_region" {
  "Mid-Atlantic"
  "Midwest"
  "Mountain"
  "New England"
  "Pacific"
  "South"
}

Enum "brokenspoke_status" {
  "pending"
  "started"
  "complete"
}

Enum "brokenspoke_step" {
  "sqs_message"
  "setup"
  "analysis"
  "cleanup"
}

Table "brokenspoke_pipeline" {
  "state_machine_id" uuid [pk, not null]
  "step" brokenspoke_step
  "sqs_message" json
  "fargate_task_arn" "character varying"
  "s3_bucket" "character varying"
  "start_time" timestamp [not null]
  "end_time" timestamp
  "torn_down" boolean
  "results_posted" boolean
  "cost" numeric
}

Table "census" {
  "census_id" integer [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "fips_code" "character varying" [not null]
  "pop_size" integer [not null]
  "population" integer [not null]

  Indexes {
    census_id [type: btree, name: "census_census_id_idx"]
    city_id [type: btree, name: "census_city_id_idx"]
  }
}

Table "city" {
  "city_id" uuid [unique, not null]
  "country" "character varying" [not null]
  "state" "character varying" [not null]
  "name" "character varying" [not null]
  "latitude" doubleprecision
  "longitude" doubleprecision
  "region" "character varying"
  "state_abbrev" "character varying"
  "speed_limit" integer
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp

  Indexes {
    (country, state, name) [pk, name: "city_pkey"]
    city_id [type: btree, name: "city_city_id_idx"]
  }
}

Table "core_services" {
  "bna_uuid" uuid [pk, not null]
  "dentists" doubleprecision
  "doctors" doubleprecision
  "grocery" doubleprecision
  "hospitals" doubleprecision
  "pharmacies" doubleprecision
  "score" doubleprecision
  "social_services" doubleprecision
}

Table "country" {
  "country_id" integer [pk, not null]
  "name" "character varying" [unique, not null]
}

Table "fargate_price" {
  "id" integer [pk, not null]
  "per_second" numeric [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "features" {
  "bna_uuid" uuid [pk, not null]
  "people" doubleprecision
  "retail" doubleprecision
  "transit" doubleprecision
}

Table "infrastructure" {
  "bna_uuid" uuid [pk, not null]
  "low_stress_miles" doubleprecision
  "high_stress_miles" doubleprecision
}

Table "opportunity" {
  "bna_uuid" uuid [pk, not null]
  "employment" doubleprecision
  "higher_education" doubleprecision
  "k12_education" doubleprecision
  "score" doubleprecision
  "technical_vocational_college" doubleprecision
}

Table "recreation" {
  "bna_uuid" uuid [pk, not null]
  "community_centers" doubleprecision
  "parks" doubleprecision
  "recreation_trails" doubleprecision
  "score" doubleprecision
}

Table "seaql_migrations" {
  "version" "character varying" [pk, not null]
  "applied_at" bigint [not null]
}

Table "speed_limit" {
  "speed_limit_id" integer [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "residential" integer [not null]

  Indexes {
    city_id [type: btree, name: "speed_limit_city_id_idx"]
    speed_limit_id [type: btree, name: "speed_limit_speed_limit_id_idx"]
  }
}

Table "state_region_crosswalk" {
  "state" "character varying" [pk, not null]
  "region" bna_region [not null]
}

Table "state_speed_limit" {
  "state_abbrev" "character (2)" [pk, not null]
  "state_fips_code" "character (2)" [not null]
  "speed" integer [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp
}

Table "submission" {
  "id" integer [pk, not null]
  "first_name" "character varying" [not null]
  "last_name" "character varying" [not null]
  "title" "character varying"
  "organization" "character varying"
  "email" "character varying" [not null]
  "country" "character varying" [not null]
  "city" "character varying" [not null]
  "region" "character varying"
  "fips_code" "character varying" [not null, default: `'0'::charactervarying`]
  "consent" boolean [not null]
  "status" approval_status [not null, default: `'Pending'::public.approval_status`]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "summary" {
  "bna_uuid" uuid [pk, not null]
  "city_id" uuid [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "score" doubleprecision [not null]
  "version" "character varying" [not null]
}

Ref "census_city_id_fkey":"city"."city_id" < "census"."city_id" [delete: cascade]

Ref "core_services_bna_uuid_fkey":"summary"."bna_uuid" < "core_services"."bna_uuid" [delete: cascade]

Ref "features_bna_uuid_fkey":"summary"."bna_uuid" < "features"."bna_uuid" [delete: cascade]

Ref "infrastructure_bna_uuid_fkey":"summary"."bna_uuid" < "infrastructure"."bna_uuid" [delete: cascade]

Ref "opportunity_bna_uuid_fkey":"summary"."bna_uuid" < "opportunity"."bna_uuid" [delete: cascade]

Ref "recreation_bna_uuid_fkey":"summary"."bna_uuid" < "recreation"."bna_uuid" [delete: cascade]

Ref "speed_limit_city_id_fkey":"city"."city_id" < "speed_limit"."city_id" [delete: cascade]

Ref "summary_city_id_fkey":"city"."city_id" < "summary"."city_id" [delete: cascade]
