name: production-deployment

on:
  push:
    branches:
      - main

permissions:
  # This is required for requesting the JWT.
  id-token: write
  # This is required for actions/checkout.
  contents: read

concurrency: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Install cargo lambda
        run: pip install cargo-lambda

      # Configure AWS and deploy the lambdas.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.LAMBDA_DEPLOY_GITHUB_ROLE_ARN_PRODUCTION }}
          aws-region: ${{ secrets.AWS_REGION_PRODUCTION }}

      # Build the lambdas in release mode and deploy them.
      - name: Build all lambdas
        run: cd lambdas && cargo lambda build --release
      - name: Deploy lambdas
        run: >
          cargo lambda deploy --iam-role ${{ secrets.BNAAPI_ROLE_ARN_PRODUCTION }}
          axumed
